# Performance Backend
backend = "glx";
glx-copy-from-front = false;

# Opacity settings
active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1.0;

# Hardware-accelerated Dual-Kawase blur
blur: {
  method = "dual_kawase";
  strength = 6;
  background = true;
  background-frame = false;
  background-fixed = false;
};

# Explicitly enforce blurring rule on suckless terminal classes
blur-background-exclude = [
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@"
];

wintypes: {
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
  dock = { shadow = false; clip-shadow-above = true; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 1.0; }
  dropdown_menu = { opacity = 1.0; }
};